version: "3.1"

networks:
  iot: 
    external:
      name: iot-bridge

services:
  conpot_default_customized:
    container_name: gridpot_praveen
    networks:
      iot:
        ipv4_address: 10.0.96.91
    build: ./
    ports:
     - "80:80" #SCADA UI, http
     - "102:102" #S7Comm
     - "502:502" #Modbus
    # - "161:16100/udp" #SNMP
    # - "47808:47808/udp" #Bacnet
    # - "623:6230/udp" #IPMI
    # - "21:2121" #FTP
    # - "69:6969/udp" #TFTP
    # - "44818:44818" #EN/IP
    restart: always

